name: malleablereality
favicon: null
layout_spectrum: 0.122383565409109
typography_spectrum: 0.5741812735795975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.37238178797997534
  lightness: 0.08801604202017188
  saturation: 0.9713537220377475
  rhythmicContrast: 0.35642817080952227
purpose: []
